### ISSUE TITLE
Perf_kernel result make error 

### ISSUE THREAD

**Issue by king32783784** [king32783784/Report_generate#2]
Traceback (most recent call last):
  File "mkresult.py", line 32, in <module>
    maincontrol._mkxls()
  File "/home/isoft_lp/桌面相关工作文档/普华桌面X86_4.x/Report_generate-1.0/processingcontrol.py", line 253, in _mkxls
    totaldata = self._getxlsdata(oslist, itemlist)
  File "/home/isoft_lp/桌面相关工作文档/普华桌面X86_4.x/Report_generate-1.0/processingcontrol.py", line 194, in _getxlsdata
    datatmp = data.datasearch_lm(pattern, "finalresult/%s/%s/result/result.out" %(os, testitem), patternnum[testitem])
  File "/home/isoft_lp/桌面相关工作文档/普华桌面X86_4.x/Report_generate-1.0/datasorting.py", line 52, in datasearch_lm
    re_list_total=re_list_new[0]
IndexError: list index out of rang

**Comment by king32783784** [comment]
lmbench　result format's setting.
